dist: xenial
language: cpp
compiler:
  - clang
  - gcc

cache:
  directories:
    - /home/travis/build/kuznetsss/pimpl_on_stack/build

addons:
  apt:
    sources:
      - llvm-toolchain-xenial-8
      - ubuntu-toolchain-r-test
    packages:
      - clang-8
      - cmake
      - gcc-9
      - g++-9


install:
  # Install conan
  - sudo pip install conan

script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-9" CC="gcc-9"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-8" CC="clang-8"; fi;
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC
  - make -j2
  - ctest --verbose